import localFont from "next/font/local";
import "./globals.css";
import Header from "@/_components/Header";
import Navbar from "@/_components/Navbar";
import { Roboto, Raleway } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const roboto = Roboto({
  subsets: ["latin"], // Include specific subsets if needed
  variable: "--font-roboto", // Define a CSS variable for the font
  weight: "500", // Range of weights to preload
  display: "swap", // Use "swap" for better UX
});

const raleway = Raleway({
  subsets: ["latin"], // Include specific subsets if needed
  variable: "--font-raleway", // Define a CSS variable for the font
  weight: "800", // Specify the font weight(s) you need
  display: "swap", // Use "swap" for better UX
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
